package me.reminisce.stats.server

import java.util.concurrent.TimeUnit

import akka.actor.{ActorSystem, Props}
import akka.io.IO
import com.github.nscala_time.time.Imports._
import com.typesafe.config.ConfigFactory
import spray.can.Http
import sun.misc.{Signal, SignalHandler}

import scala.concurrent.ExecutionContext
import scala.concurrent.duration.Duration

/**
  * Application entry point.
  */
object Server extends App {

  val conf = ConfigFactory.load()
  // an ActorSystem to host our application in
  implicit val system = ActorSystem("server", conf)
  implicit val context = ExecutionContext.Implicits.global

  val protocol = "http://"
  val port = ApplicationConfiguration.serverPort
  val hostName = ApplicationConfiguration.hostName
  val mongoHost = ApplicationConfiguration.mongoHost
  val mongoDbName = ApplicationConfiguration.mongodbName
  // create and start our service actor
  val service = system.actorOf(Props(new StatsServerActor(mongoHost, mongoDbName)), "server-service")
  println("ServerServiceActor created")

  // sets the default timezone to UTC
  DateTimeZone.setDefault(DateTimeZone.forID("UTC"))

  // start a new HTTP server on port 7777 with our service actor as the handler
  IO(Http) ! Http.Bind(service, interface = hostName, port = port)

  // Handles the INT signal (unix signal 2, usually generated by a ^C) to shutdown gracefully
  Signal.handle(new Signal("INT"), new SignalHandler() {
    def handle(sig: Signal) {
      shutdown()
    }
  })

  // Handles the TERM signal (unix signal 15) to shutdown gracefully
  Signal.handle(new Signal("TERM"), new SignalHandler() {
    def handle(sig: Signal) {
      shutdown()
    }
  })

  /**
    * Shuts the system down in a proper way.
    */
  private def shutdown(): Unit = {
    println("System is shutting down...")
    IO(Http) ! Http.Unbind(Duration(10, TimeUnit.SECONDS))
    system.terminate()
  }
}
